version: "3.4"

services:

  jikan-rest-api:
    build:
      context: jikan
      dockerfile: Dockerfile
    depends_on:
      - jikan-redis-db
    ports:
      - "9001:80"
    networks:
      - default
    restart: always

  jikan-redis-db:
    image: redis
    restart: always
